/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as InstructorLoginRouteImport } from './routes/instructor-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SelfReportRouteImport } from './routes/self-report'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminManageRouteImport } from './routes/admin/manage'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as InstructorEvaluateRouteImport } from './routes/instructor/evaluate'
import { Route as InstructorInstructorsRouteImport } from './routes/instructor/instructors'
import { Route as InstructorLeaderboardRouteImport } from './routes/instructor/leaderboard'
import { Route as InstructorMessagesRouteImport } from './routes/instructor/messages'
import { Route as InstructorSettingsRouteImport } from './routes/instructor/settings'
import { Route as InstructorStudentsRouteImport } from './routes/instructor/students'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentAttendanceRouteImport } from './routes/student/attendance'
import { Route as StudentLeaderboardRouteImport } from './routes/student/leaderboard'
import { Route as StudentMessagesRouteImport } from './routes/student/messages'
import { Route as StudentProgressRouteImport } from './routes/student/progress'
import { Route as StudentSelfReportRouteImport } from './routes/student/self-report'
import { Route as InstructorStudentsIdRouteImport } from './routes/instructor/students.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorLoginRoute = InstructorLoginRouteImport.update({
  id: '/instructor-login',
  path: '/instructor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfReportRoute = SelfReportRouteImport.update({
  id: '/self-report',
  path: '/self-report',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorEvaluateRoute = InstructorEvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorInstructorsRoute = InstructorInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorLeaderboardRoute = InstructorLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorMessagesRoute = InstructorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorSettingsRoute = InstructorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorStudentsRoute = InstructorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => InstructorRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSelfReportRoute = StudentSelfReportRouteImport.update({
  id: '/self-report',
  path: '/self-report',
  getParentRoute: () => StudentRoute,
} as any)
const InstructorStudentsIdRoute = InstructorStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InstructorStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/attendance': typeof AttendanceRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/edit-profile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRouteWithChildren
  '/instructor-login': typeof InstructorLoginRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/self-report': typeof SelfReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/manage': typeof AdminManageRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/instructor/evaluate': typeof InstructorEvaluateRoute
  '/instructor/instructors': typeof InstructorInstructorsRoute
  '/instructor/leaderboard': typeof InstructorLeaderboardRoute
  '/instructor/messages': typeof InstructorMessagesRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/instructor/students': typeof InstructorStudentsRouteWithChildren
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/self-report': typeof StudentSelfReportRoute
  '/admin/': typeof AdminIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/instructor/students/$id': typeof InstructorStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/attendance': typeof AttendanceRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/edit-profile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor-login': typeof InstructorLoginRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/self-report': typeof SelfReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/instructor/evaluate': typeof InstructorEvaluateRoute
  '/instructor/instructors': typeof InstructorInstructorsRoute
  '/instructor/leaderboard': typeof InstructorLeaderboardRoute
  '/instructor/messages': typeof InstructorMessagesRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/instructor/students': typeof InstructorStudentsRouteWithChildren
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/self-report': typeof StudentSelfReportRoute
  '/admin': typeof AdminIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/student': typeof StudentIndexRoute
  '/instructor/students/$id': typeof InstructorStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/attendance': typeof AttendanceRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/edit-profile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRouteWithChildren
  '/instructor-login': typeof InstructorLoginRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/self-report': typeof SelfReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/manage': typeof AdminManageRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/instructor/evaluate': typeof InstructorEvaluateRoute
  '/instructor/instructors': typeof InstructorInstructorsRoute
  '/instructor/leaderboard': typeof InstructorLeaderboardRoute
  '/instructor/messages': typeof InstructorMessagesRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/instructor/students': typeof InstructorStudentsRouteWithChildren
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/self-report': typeof StudentSelfReportRoute
  '/admin/': typeof AdminIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/instructor/students/$id': typeof InstructorStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/attendance'
    | '/change-password'
    | '/dashboard'
    | '/edit-profile'
    | '/forgot-password'
    | '/instructor'
    | '/instructor-login'
    | '/login'
    | '/messages'
    | '/register'
    | '/reset-password'
    | '/self-report'
    | '/sitemap.xml'
    | '/student'
    | '/admin/manage'
    | '/admin/settings'
    | '/instructor/evaluate'
    | '/instructor/instructors'
    | '/instructor/leaderboard'
    | '/instructor/messages'
    | '/instructor/settings'
    | '/instructor/students'
    | '/student/attendance'
    | '/student/leaderboard'
    | '/student/messages'
    | '/student/progress'
    | '/student/self-report'
    | '/admin/'
    | '/instructor/'
    | '/student/'
    | '/instructor/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/attendance'
    | '/change-password'
    | '/dashboard'
    | '/edit-profile'
    | '/forgot-password'
    | '/instructor-login'
    | '/login'
    | '/messages'
    | '/register'
    | '/reset-password'
    | '/self-report'
    | '/sitemap.xml'
    | '/admin/manage'
    | '/admin/settings'
    | '/instructor/evaluate'
    | '/instructor/instructors'
    | '/instructor/leaderboard'
    | '/instructor/messages'
    | '/instructor/settings'
    | '/instructor/students'
    | '/student/attendance'
    | '/student/leaderboard'
    | '/student/messages'
    | '/student/progress'
    | '/student/self-report'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/instructor/students/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/attendance'
    | '/change-password'
    | '/dashboard'
    | '/edit-profile'
    | '/forgot-password'
    | '/instructor'
    | '/instructor-login'
    | '/login'
    | '/messages'
    | '/register'
    | '/reset-password'
    | '/self-report'
    | '/sitemap.xml'
    | '/student'
    | '/admin/manage'
    | '/admin/settings'
    | '/instructor/evaluate'
    | '/instructor/instructors'
    | '/instructor/leaderboard'
    | '/instructor/messages'
    | '/instructor/settings'
    | '/instructor/students'
    | '/student/attendance'
    | '/student/leaderboard'
    | '/student/messages'
    | '/student/progress'
    | '/student/self-report'
    | '/admin/'
    | '/instructor/'
    | '/student/'
    | '/instructor/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AttendanceRoute: typeof AttendanceRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  EditProfileRoute: typeof EditProfileRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InstructorRoute: typeof InstructorRouteWithChildren
  InstructorLoginRoute: typeof InstructorLoginRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelfReportRoute: typeof SelfReportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor-login': {
      id: '/instructor-login'
      path: '/instructor-login'
      fullPath: '/instructor-login'
      preLoaderRoute: typeof InstructorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-report': {
      id: '/self-report'
      path: '/self-report'
      fullPath: '/self-report'
      preLoaderRoute: typeof SelfReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage': {
      id: '/admin/manage'
      path: '/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/evaluate': {
      id: '/instructor/evaluate'
      path: '/evaluate'
      fullPath: '/instructor/evaluate'
      preLoaderRoute: typeof InstructorEvaluateRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/instructors': {
      id: '/instructor/instructors'
      path: '/instructors'
      fullPath: '/instructor/instructors'
      preLoaderRoute: typeof InstructorInstructorsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/leaderboard': {
      id: '/instructor/leaderboard'
      path: '/leaderboard'
      fullPath: '/instructor/leaderboard'
      preLoaderRoute: typeof InstructorLeaderboardRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/messages': {
      id: '/instructor/messages'
      path: '/messages'
      fullPath: '/instructor/messages'
      preLoaderRoute: typeof InstructorMessagesRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/settings': {
      id: '/instructor/settings'
      path: '/settings'
      fullPath: '/instructor/settings'
      preLoaderRoute: typeof InstructorSettingsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/students': {
      id: '/instructor/students'
      path: '/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/self-report': {
      id: '/student/self-report'
      path: '/self-report'
      fullPath: '/student/self-report'
      preLoaderRoute: typeof StudentSelfReportRouteImport
      parentRoute: typeof StudentRoute
    }
    '/instructor/students/$id': {
      id: '/instructor/students/$id'
      path: '/$id'
      fullPath: '/instructor/students/$id'
      preLoaderRoute: typeof InstructorStudentsIdRouteImport
      parentRoute: typeof InstructorStudentsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminManageRoute: typeof AdminManageRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminManageRoute: AdminManageRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InstructorStudentsRouteChildren {
  InstructorStudentsIdRoute: typeof InstructorStudentsIdRoute
}

const InstructorStudentsRouteChildren: InstructorStudentsRouteChildren = {
  InstructorStudentsIdRoute: InstructorStudentsIdRoute,
}

const InstructorStudentsRouteWithChildren =
  InstructorStudentsRoute._addFileChildren(InstructorStudentsRouteChildren)

interface InstructorRouteChildren {
  InstructorEvaluateRoute: typeof InstructorEvaluateRoute
  InstructorInstructorsRoute: typeof InstructorInstructorsRoute
  InstructorLeaderboardRoute: typeof InstructorLeaderboardRoute
  InstructorMessagesRoute: typeof InstructorMessagesRoute
  InstructorSettingsRoute: typeof InstructorSettingsRoute
  InstructorStudentsRoute: typeof InstructorStudentsRouteWithChildren
  InstructorIndexRoute: typeof InstructorIndexRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorEvaluateRoute: InstructorEvaluateRoute,
  InstructorInstructorsRoute: InstructorInstructorsRoute,
  InstructorLeaderboardRoute: InstructorLeaderboardRoute,
  InstructorMessagesRoute: InstructorMessagesRoute,
  InstructorSettingsRoute: InstructorSettingsRoute,
  InstructorStudentsRoute: InstructorStudentsRouteWithChildren,
  InstructorIndexRoute: InstructorIndexRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

interface StudentRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentSelfReportRoute: typeof StudentSelfReportRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentSelfReportRoute: StudentSelfReportRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AttendanceRoute: AttendanceRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  EditProfileRoute: EditProfileRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InstructorRoute: InstructorRouteWithChildren,
  InstructorLoginRoute: InstructorLoginRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelfReportRoute: SelfReportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
